#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

DFLT_MODEFILE=".git-mode-cache"
USAGE="Usage:
    ${0##*/} save OPTIONS
or  ${0##*/} restore OPTIONS

Save or restore permissions of files in a git repository.

Options:
  -f file:  Save permissions to (or load from) file (default: ${DFLT_MODEFILE})
            Note: if a relative path is supplied, it is interpreted relative to
            the repository root.
  -h:       Show this help and exit.
"

function go_worktree_root() {
  local CDUP
  CDUP=$(git rev-parse --show-cdup)

  if [[ "${CDUP}" ]]; then
    pushd "${CDUP}" &> /dev/null
    trap 'popd &> /dev/null' EXIT
  fi
}

function files_ancestors() {
  local FPATH

  while read -r -d '' FPATH; do
    while [[ "${FPATH}" && "${FPATH}" != [./] ]]; do
      printf "%s\0" "${FPATH}"
      FPATH=$(dirname "${FPATH}")
    done
  done
}

function filter_symlinks() {
  local FILENAME

  while read -r -d '' FILENAME; do
    if [[ ! -L "${FILENAME}" ]]; then
      printf "%s\0" "${FILENAME}"
    fi
  done
}

function get_modes() {
  local -a STATOPTS=(--printf '%a\t%n\0')
  local STAT

  if stat --printf '' . &> /dev/null; then
    STAT=stat
  else
    STAT=gstat
  fi

  git ls-files -cz --full-name \
    | files_ancestors \
    | filter_symlinks \
    | sort -zu \
    | xargs -0 "${STAT}" "${STATOPTS[@]}"
}

function restore_modes() {
  local MODE
  local FILENAME
  local ORIG_IFS="${IFS}"

  printf -v IFS '\t'

  while read -r -d '' MODE FILENAME; do
    if [[ ! -L "${FILENAME}" ]]; then
      chmod "${MODE}" "${FILENAME}"
    fi
  done

  IFS="${ORIG_IFS}"
}

function process_args() {
  local OPTIND=1
  local -n CMD=$1
  local -n FNAME=$2

  CMD=${3^^*}
  FNAME="${DFLT_MODEFILE}"

  shift 3

  while getopts 'f:h' OPT; do
    case "${OPT}" in
      'f')
        MODEFILE=${OPTARG}
        ;;
      'h')
        echo "${USAGE}"
        exit
        ;;
      *)
        echo "${USAGE}" >&2
        exit 1
        ;;
    esac
  done

  shift $((OPTIND-1))

  if [[ $# -gt 0 ]]; then
    echo "Unexpected arguments: $@" >&2
    echo "${USAGE}" >&2
    exit 1
  fi
}

function main() {
  local COMMAND
  local MODEFILE

  process_args COMMAND MODEFILE "$@"

  go_worktree_root

  case "${COMMAND}" in
    "SAVE")
      get_modes > "${MODEFILE}"
      ;;

    "RESTORE")
      restore_modes < "${MODEFILE}"
      ;;

    *)
      echo "${USAGE}" >&2
      exit 1
      ;;
  esac
}

main "$@"
